# Generated by Django 4.1.3 on 2022-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221101_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmember', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=25)),
                ('alamat', models.CharField(max_length=30)),
            ],
        ),
    ]
